name: emotion_detector
channels:
  - conda-forge
dependencies:
  - python=3.11
  - tensorflow-cpu=2.19.1
  - keras=3.13.2
  - opencv=4.13.0
  - numpy=2.4.2
  - pandas=3.0.0
  - matplotlib=3.10.8
  - scikit-learn=1.8.0
  - seaborn=0.13.2
  - tensorboard=2.19.0
  - pillow=12.1.1
  - h5py=3.15.1
  - tqdm=4.67.3
  - scipy=1.17.0
  - jupyterlab=4.5.4
